CREATE TABLE  IF NOT EXISTS Odontologos (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(80), apellido VARCHAR(80), matricula VARCHAR(10));

CREATE TABLE  IF NOT EXISTS Pacientes (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(80), apellido VARCHAR(80), domicilio VARCHAR(255), dni VARCHAR(9));
